apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-aggo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xmfq-tenant/rhtap-demo-app/hacbs-test-project-aggo@sha256:7dae24fdebe061c9b080b00a219cade68d554af4a5c935d4b8b2e8dede38d11b
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
