apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-aggo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xmfq-tenant/rhtap-demo-app/hacbs-test-project-aggo@sha256:9b21e16974bd1b40767edfa9b08242eda853ce328f6081390b82f26734a8ede0
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
